### ISSUE TITLE
ArrayAccess compatibility

### ISSUE THREAD

**Issue by natebrunette** [morrisonlevi/php-generics-design-library#1]
https://github.com/morrisonlevi/php-generics-design-library/blob/728fde4705f42c7050a8c7da7011cecc83fe8fbf/src/interfaces.php#L27

One side affect you've possibly already considered is that that specific generic implementations of `ArrayAccess` would not be compatible type-hinted `ArrayAccess`

The following would not work because `K` is contravariant and `V` is invariant to `mixed`

```php
class MyArrayAccess<in K, V> implements ArrayAccess<K, V> { /* ... */ }

function foo(ArrayAccess $array) {}

foo(new MyArrayAccess<int, string>());
```

If `ArrayAccess` was not generic, I believe that this would work fine.

**Comment by morrisonlevi** [comment]
I believe this is intentional: the new code *is not* compatible with the old. That foo function had no constraints on keys or values and there would be runtime type errors when adding incompatible keys or values to the object.

The fix is to make `foo` generic as well:

    function foo<K,V>(ArrayAccess<K,V> $array) {}

That is, if whatever it does really is generic.

Does that make sense? Any weaknesses to the argument?

**Comment by natebrunette** [comment]
Yeah, I think that makes sense. We can update core interfaces in a BC manner and people can start using them, but integration with existing libraries/APIs using those interfaces will require updates.
